# Generated by Django 5.0.6 on 2024-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
