# Generated by Django 5.0.6 on 2024-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_usuarios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=25),
        ),
    ]
