# Generated by Django 5.0.6 on 2024-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_usuarios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nivel',
            field=models.CharField(default='3', max_length=25),
        ),
    ]
