# Generated by Django 5.0.6 on 2024-06-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_usuarios_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nivel',
            field=models.CharField(max_length=25),
        ),
    ]
